"""Generate service requirements files from pyproject.toml + uv.lock.

FlowMesh has three generated requirements files:

- `src/server/requirements.txt` — the unified server (orchestrator + supervisor).
- `src/worker/requirements/requirements.txt` — the worker CPU layer.
- `src/worker/requirements/requirements.gpu.txt` — the worker GPU-only delta
  layered on top of the CPU layer.

Each file enumerates the DIRECT dependencies of a curated set of runtime
dependency groups, pinned to the exact version resolved by uv.lock.
Transitives are deliberately not listed so the same pin list works across CPU
and GPU torch backends — triton, nvidia-cu*, etc. are picked up by uv at
install time according to UV_TORCH_BACKEND.

Run with no arguments to check for drift against the committed files; run
with ``--write`` to regenerate them in place.
"""

import argparse
import difflib
import re
import subprocess
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PYPROJECT = REPO_ROOT / "pyproject.toml"
SERVER_REQ = REPO_ROOT / "src" / "server" / "requirements.txt"
WORKER_CPU_REQ = REPO_ROOT / "src" / "worker" / "requirements" / "requirements.txt"
WORKER_GPU_REQ = REPO_ROOT / "src" / "worker" / "requirements" / "requirements.gpu.txt"

SERVER_GROUPS: list[str] = ["runtime-server"]

# Worker CPU layer: Dockerfile.cpu, and Dockerfile.cuda runtime stage.
WORKER_CPU_GROUPS: list[str] = [
    "runtime-worker-core",
    "runtime-inference",
    "runtime-training",
    "runtime-rag",
    "runtime-agent",
    "runtime-analytics",
    "runtime-observability",
]

# Worker GPU-only deltas, installed in the cuda.builder stage.
WORKER_GPU_GROUPS: list[str] = [
    "runtime-inference-gpu",
    "runtime-training-gpu",
]

# The only alternate index this project vends from — flashinfer wheels built
# for cu129. See src/worker/docker/Dockerfile.cuda.builder (UV_TORCH_BACKEND=cu129).
# `uv export` does not emit --extra-index-url into the generated file.
FLASHINFER_INDEX = "https://flashinfer.ai/whl/cu129"

# Precompiled flashinfer kernels, pinned to match the `flashinfer-python`
# version resolved from uv.lock. They are published only on FLASHINFER_INDEX,
# not on PyPI, so we can't declare them in pyproject — `uv lock` would mark the
# workspace unsatisfiable. Appended directly to requirements.gpu.txt; the
# `--extra-index-url` directive above tells the Docker install step where to
# fetch them.
FLASHINFER_EXTRAS: tuple[str, ...] = ("flashinfer-jit-cache",)

HEADER = (
    "# AUTO-GENERATED by scripts/dev/sync_requirements.py — do not edit by hand.\n"
    "# Regenerate with: uv run scripts/dev/sync_requirements.py --write\n"
)

_PKG_RE = re.compile(r"^([A-Za-z0-9_.-]+)(\[[^\]]+\])?(?:\s*[@<>=!~].*)?$")


def _direct_deps(groups: list[str]) -> dict[str, str]:
    with PYPROJECT.open("rb") as f:
        data = tomllib.load(f)
    dependency_groups = data["dependency-groups"]
    deps: dict[str, str] = {}
    for group in groups:
        if group not in dependency_groups:
            raise SystemExit(
                f"Group {group!r} not found in pyproject.toml " "[dependency-groups]."
            )
        for spec in dependency_groups[group]:
            if not isinstance(spec, str):
                raise SystemExit(
                    f"Group {group!r} contains an include or non-string entry. "
                    "Use leaf runtime groups when generating requirements."
                )
            m = _PKG_RE.match(spec.strip())
            if not m:
                continue
            name = m.group(1).lower().replace("_", "-")
            marker = m.group(2) or ""
            if marker and len(marker) > len(deps.get(name, "")):
                deps[name] = marker
            else:
                deps.setdefault(name, marker)
    return deps


def _uv_export(groups: list[str]) -> list[str]:
    cmd = [
        "uv",
        "export",
        "--frozen",
        "--no-dev",
        "--no-default-groups",
        "--no-hashes",
        "--no-emit-project",
        "--format",
        "requirements-txt",
    ]
    for group in groups:
        cmd += ["--group", group]
    result = subprocess.run(
        cmd, cwd=REPO_ROOT, capture_output=True, text=True, check=True
    )
    pins: list[str] = []
    for raw in result.stdout.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("-e "):
            continue
        pins.append(line)
    return pins


def _line_pkg(line: str) -> str:
    head = line.split(";", 1)[0].strip()
    m = re.match(r"^([A-Za-z0-9_.-]+)", head)
    if not m:
        return ""
    return m.group(1).lower().replace("_", "-")


def _filter_direct(pins: list[str], keep: dict[str, str]) -> list[str]:
    out: list[str] = []
    for pin in pins:
        name = _line_pkg(pin)
        if name not in keep:
            continue
        marker = keep[name]
        if not marker:
            out.append(pin)
            continue
        head, sep, tail = pin.partition("==")
        out.append(f"{head.strip()}{marker}{sep}{tail.strip()}" if sep else pin)
    return sorted(out, key=str.lower)


def render(groups: list[str]) -> str:
    direct = _direct_deps(groups)
    lines = _filter_direct(_uv_export(groups), direct)
    return HEADER + "\n".join(lines) + "\n"


def render_worker_gpu() -> str:
    cpu_direct = _direct_deps(WORKER_CPU_GROUPS)
    gpu_direct = {
        name: marker
        for name, marker in _direct_deps(WORKER_GPU_GROUPS).items()
        if name not in cpu_direct
    }
    pins = _uv_export(WORKER_CPU_GROUPS + WORKER_GPU_GROUPS)
    lines = _filter_direct(pins, gpu_direct)
    flashinfer_version = next(
        (p.split("==", 1)[1] for p in pins if _line_pkg(p) == "flashinfer-python"),
        None,
    )
    if flashinfer_version is not None:
        for extra in FLASHINFER_EXTRAS:
            lines.append(f"{extra}=={flashinfer_version}")
        lines.sort(key=str.lower)
    return f"{HEADER}--extra-index-url {FLASHINFER_INDEX}\n" + "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="Overwrite the committed requirements files with generated output.",
    )
    args = parser.parse_args()

    targets: list[tuple[Path, str]] = [
        (SERVER_REQ, render(SERVER_GROUPS)),
        (WORKER_CPU_REQ, render(WORKER_CPU_GROUPS)),
        (WORKER_GPU_REQ, render_worker_gpu()),
    ]

    mismatches: list[str] = []
    for path, rendered in targets:
        rel = path.relative_to(REPO_ROOT)
        if args.write:
            path.write_text(rendered)
            print(f"Wrote {rel}")
            continue
        current = path.read_text() if path.exists() else ""
        if current != rendered:
            mismatches.append(str(rel))
            diff = difflib.unified_diff(
                current.splitlines(),
                rendered.splitlines(),
                fromfile=str(rel),
                tofile=f"{rel} (generated)",
                lineterm="",
            )
            sys.stdout.write("\n".join(diff) + "\n")

    if mismatches and not args.write:
        print("\nMismatched requirements files:")
        for path_str in mismatches:
            print(f"- {path_str}")
        print("\nRun `uv run scripts/dev/sync_requirements.py --write` to regenerate.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
