[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flowmesh-sdk-stack"
version = "0.1.8"
description = "FlowMesh SDK stack client"
readme = "README.md"
requires-python = ">=3.12"
license = "Apache-2.0"
license-files = ["LICENSE"]
dependencies = [
    "flowmesh-sdk==0.1.8",
    "httpx>=0.27.0",
    "pyyaml>=6.0.0",
    "docker>=7.1.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
